### ISSUE TITLE
Comment généraliser les tests pour la classe EfficientPerson

### ISSUE THREAD

**Issue by TyrkoDev** [PolytechLyon/4a-isi3-tp3-2016-2017-groupe-1-chirat_deschamps#2]
Bonjour,

Désolé pour cette question de dernière minute, je ne comprends vraiment pas comment faire en sorte que les tests fonctionnent sur la class EfficientPerson étant donnée qu'elle n'a pas de date de naissance mais uniquement un âge. Si vous pouvez me donner un indice ce serait top ! Sinon le reste est implémenté et commenté dans le rapport. Merci d'avance !

**Comment by Slashgear** [comment]
Il faudrait passer par un pattern pour adapter ton efficient personne  ;)

**Comment by TyrkoDev** [comment]
Ok, merci beaucoup 👍

**Comment by TyrkoDev** [comment]
ça fonctionne correctement maintenant !
